 name: Repo Generic Testing Workflow

on:
  push:
    branches:
      - testing-nexus-speed

jobs:  
  nexus-cloud:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        iteration: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Maven Settings
        shell: bash
        run: |
          echo ${{ SECRETS.NEXUS_CLOUD_SETTINGS_XML }} | base64 --decode > ./settings.xml
      - name: Set up JDK
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          overwrite-settings: false

      - name: Record start time
        id: start
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Maven Clean
        shell: bash
        run: |
          mvn clean compile --settings settings.xml
      - name: Write runtime to job summary
        if: always()
        run: |
          end_time=$(date +%s)
          duration=$(( end_time - start_time ))
          mins=$(( duration / 60 ))
          secs=$(( duration % 60 ))
          {
            echo "### Iteration ${{ matrix.iteration }}"
            echo ""
            echo "⏱ Took **${mins}m ${secs}s**"
            echo ""
          } >> $GITHUB_STEP_SUMMARY
